// Jenkinsfile
pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'mvn -f src/user-service clean package'
      }
    }
    stage('Test') {
      steps {
        sh 'mvn -f src/user-service test'
      }
    }
    stage('SonarQube Analysis') {
      steps {
        withSonarQubeEnv('sonar-server') {
          sh 'mvn -f src/user-service sonar:sonar'
        }
      }
    }
    stage('Build Docker Image') {
      steps {
        script {
          docker.build("jfrog.io/myproject/user-service:${env.BUILD_ID}")
        }
      }
    }
    stage('Deploy to K8s') {
      steps {
        sh "python3 jenkins/scripts/deploy-to-k8s.py user-service"
      }
    }
  }
}
